name: Docs

on:
  workflow_dispatch:
  push:
    branches:
    - master
    paths:
    - QuickStart/src/**
    - QuickStart/docs/**
    - .github/workflows/publish-github-pages.yml
  pull_request:
    branches:
    - main
    paths:
    - QuickStart/docs/**
    - .github/workflows/publish-github-pages.yml

jobs:
  generate-docs:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Setup DocFX & tools
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install docfx docfx-companion-tools

    - name: Generate table of content
      working-directory: QuickStart
      run: docfxtocgenerator -d ./docs -sri
      continue-on-error: false

    - name: DocFX Build
      working-directory: QuickStart
      run: docfx .\docfx.json
      continue-on-error: false

    - name: Publish
      if: github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: QuickStart/_site
        force_orphan: true